# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
display(applicant_data_df)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Review the data types associated with the columns
print(applicant_data_df.dtypes)

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop('EIN', axis = 1)

# Review the DataFrame
display(applicant_data_df)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = list(set( applicant_data_df.columns) - set(applicant_data_df._get_numeric_data().columns))

# Display the categorical variables list
print(categorical_variables)

['APPLICATION_TYPE', 'CLASSIFICATION', 'AFFILIATION', 'INCOME_AMT', 'USE_CASE', 'ORGANIZATION', 'SPECIAL_CONSIDERATIONS', 'NAME']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder()

In [7]:
applicant_data_df[categorical_variables].to_numpy().shape

(34299, 8)

In [8]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables].to_numpy())
encoded_data

<34299x19682 sparse matrix of type '<class 'numpy.float64'>'
	with 274392 stored elements in Compressed Sparse Row format>

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data.toarray())

# Review the DataFrame
display(encoded_df)

,0,1,2,3,4,5,6,7,8,9,...,19672,19673,19674,19675,19676,19677,19678,19679,19680,19681
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df[applicant_data_df._get_numeric_data().columns]], axis = 1)

# Review the Dataframe
display(encoded_df)

,0,1,2,3,4,5,6,7,8,9,...,19675,19676,19677,19678,19679,19680,19681,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [11]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
display(y)

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [12]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop('IS_SUCCESSFUL', axis = 1)

# Review the features DataFrame
X

,0,1,2,3,4,5,6,7,8,9,...,19674,19675,19676,19677,19678,19679,19680,19681,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,5000
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [27]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y)

MemoryError: Unable to allocate 3.77 GiB for an array with shape (19682, 25724) and data type float64

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [24]:
# Create a StandardScaler instance
#scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

NameError: name 'scaler' is not defined

In [25]:
X_train_scaled.shape

NameError: name 'X_train_scaled' is not defined

In [26]:
X_train.shape

(25724, 19684)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [18]:
# Define the the number of inputs (features) to the model
number_input_features = 19684

# Review the number of features
print(number_input_features)

19684

In [19]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [20]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  8

# Review the number hidden nodes in the first layer
print(hidden_nodes_layer1)

8

In [21]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  8

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

8

In [22]:
# Create the Sequential model instance
nn = tf.keras.Sequential()

In [23]:
# Add the first hidden layer
nn.add(tf.keras.layers.Dense(hidden_nodes_layer1, input_shape = (number_input_features,)))

In [ ]:
# Add the second hidden layer
nn.add(tf.keras.layers.Dense(hidden_nodes_layer2))

In [ ]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

In [ ]:
# Display the Sequential model summary
nn.summary()

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [ ]:
# Compile the Sequential model
nn.compile(optimizer = 'adam', metrics = ['accuracy'], loss = 'binary_crossentropy')

In [ ]:
# Fit the model using 50 epochs and the training data
# YOUR CODE HERE
nn.fit(X_train_scaled, y_train.to_numpy().reshape(-1,1), epochs = 50)

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [ ]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test.to_numpy().reshape(-1,1))

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [ ]:
# Set the model's file path
file_path = 'AlphabetSoup.h5'

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [21]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

NameError: name 'X_train' is not defined

In [22]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [35]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 16

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

16

In [40]:
# Create the Sequential model instance
nn_A1 = tf.keras.Sequential()

In [41]:
# First hidden layer
nn_A1.add(tf.keras.layers.Dense(hidden_nodes_layer1_A1, input_shape = (number_input_features,), activation = 'relu'))
nn_A1.add(tf.keras.layers.Dense(16, activation = 'relu'))
nn_A1.add(tf.keras.layers.Dense(16, activation = 'relu'))
nn_A1.add(tf.keras.layers.Dense(16, activation = 'relu'))
nn_A1.add(tf.keras.layers.Dense(16, activation = 'relu'))

# Output layer
nn_A1.add(tf.keras.layers.Dense(number_output_neurons_A1, activation = 'sigmoid'))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_9 (Dense)              (None, 8)                 157480
_________________________________________________________________
dense_10 (Dense)             (None, 16)                144
_________________________________________________________________
dense_11 (Dense)             (None, 16)                272
_________________________________________________________________
dense_12 (Dense)             (None, 16)                272
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 136
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 9
=================================================================
Total params: 158,313
Trainable params: 158,313
Non-trainable params: 0
_________________________________________________________________

In [42]:
# Compile the Sequential model
nn_A1.compile(optimizer = 'adam', metrics = ['accuracy'], loss = 'binary_crossentropy')

In [43]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/20
804/804 [==============================] - 3s 4ms/step - loss: 0.5015 - accuracy: 0.7532
Epoch 2/20
804/804 [==============================] - 3s 3ms/step - loss: 0.3587 - accuracy: 0.8317
Epoch 3/20
804/804 [==============================] - 3s 3ms/step - loss: 0.2082 - accuracy: 0.9149: 1s - loss: 0.2103 - accuracy - ETA: 1s - loss: 0.209 - ETA: 0s - loss: 0
Epoch 4/20
804/804 [==============================] - 3s 3ms/step - loss: 0.1345 - accuracy: 0.9488
Epoch 5/20
804/804 [==============================] - 3s 3ms/step - loss: 0.1112 - accuracy: 0.9588
Epoch 6/20
804/804 [==============================] - 3s 3ms/step - loss: 0.1044 - accuracy: 0.9593
Epoch 7/20
804/804 [==============================] - 3s 3ms/step - loss: 0.1009 - accuracy: 0.9603
Epoch 8/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0988 - accuracy: 0.9613
Epoch 9/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0976 - accuracy: 0.9611: 0s - loss: 0
Epoch 10/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0963 - accuracy: 0.9619
Epoch 11/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0955 - accuracy: 0.9627
Epoch 12/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0952 - accuracy: 0.9625
Epoch 13/20
804/804 [==============================] - ETA: 0s - loss: 0.0964 - accuracy: 0.96 - 3s 3ms/step - loss: 0.0967 - accuracy: 0.9626
Epoch 14/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0991 - accuracy: 0.9613
Epoch 15/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0967 - accuracy: 0.9622
Epoch 16/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0930 - accuracy: 0.9638
Epoch 17/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0927 - accuracy: 0.9633
Epoch 18/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0926 - accuracy: 0.9642
Epoch 19/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0960 - accuracy: 0.9632: 0s - loss: 0
Epoch 20/20
804/804 [==============================] - 3s 3ms/step - loss: 0.0973 - accuracy: 0.9623

#### Alternative Model 2

In [46]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

19684

In [47]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [48]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 8

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

32

In [49]:
# Create the Sequential model instance
nn_A2 = tf.keras.Sequential()

In [50]:
# First hidden layer
nn_A2.add(tf.keras.layers.Dense(hidden_nodes_layer1_A2, input_shape = (number_input_features,), activation = 'sigmoid'))
nn_A2.add(tf.keras.layers.Dense(16, activation = 'sigmoid'))
nn_A2.add(tf.keras.layers.Dense(16, activation = 'sigmoid'))
nn_A2.add(tf.keras.layers.Dense(16, activation = 'sigmoid'))
nn_A2.add(tf.keras.layers.Dense(8, activation = 'sigmoid'))

# Output layer
nn_A2.add(tf.keras.layers.Dense(number_output_neurons_A2, activation = 'sigmoid'))


# Check the structure of the model
nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_15 (Dense)             (None, 8)                 157480
_________________________________________________________________
dense_16 (Dense)             (None, 16)                144
_________________________________________________________________
dense_17 (Dense)             (None, 16)                272
_________________________________________________________________
dense_18 (Dense)             (None, 16)                272
_________________________________________________________________
dense_19 (Dense)             (None, 8)                 136
_________________________________________________________________
dense_20 (Dense)             (None, 1)                 9
=================================================================
Total params: 158,313
Trainable params: 158,313
Non-trainable params: 0
_________________________________________________________________

In [51]:
# Compile the Sequential model
nn_A2.compile(optimizer = 'adam', metrics = ['accuracy'], loss = 'binary_crossentropy')

In [53]:
# Fit the model using 50 epochs and the training data
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
804/804 [==============================] - 3s 4ms/step - loss: 0.6678 - accuracy: 0.5946
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4005 - accuracy: 0.8560
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.2666 - accuracy: 0.9158
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.1508 - accuracy: 0.9558
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.1252 - accuracy: 0.9591
Epoch 6/50
804/804 [==============================] - 3s 3ms/step - loss: 0.1116 - accuracy: 0.9626
Epoch 7/50
804/804 [==============================] - 3s 3ms/step - loss: 0.1046 - accuracy: 0.9628
Epoch 8/50
804/804 [==============================] - 3s 3ms/step - loss: 0.1008 - accuracy: 0.9635
Epoch 9/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0987 - accuracy: 0.9635
Epoch 10/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0974 - accuracy: 0.9637
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0964 - accuracy: 0.9640: 1s - loss: 0 - ETA: 0s - l
Epoch 12/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0951 - accuracy: 0.9640
Epoch 13/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0944 - accuracy: 0.9642: 0s - los
Epoch 14/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0934 - accuracy: 0.9643
Epoch 15/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0932 - accuracy: 0.9642
Epoch 16/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0924 - accuracy: 0.9647
Epoch 17/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0918 - accuracy: 0.9647
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0912 - accuracy: 0.9647
Epoch 19/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0906 - accuracy: 0.9649
Epoch 20/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0897 - accuracy: 0.9649
Epoch 21/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0898 - accuracy: 0.9650
Epoch 22/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0894 - accuracy: 0.9650
Epoch 23/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0887 - accuracy: 0.9657: 0s - loss: 0.0887
Epoch 24/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0884 - accuracy: 0.9652
Epoch 25/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0882 - accuracy: 0.9658
Epoch 26/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0879 - accuracy: 0.9657
Epoch 27/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0876 - accuracy: 0.9659
Epoch 28/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0876 - accuracy: 0.9661
Epoch 29/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0878 - accuracy: 0.9661
Epoch 30/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0878 - accuracy: 0.9656
Epoch 31/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0868 - accuracy: 0.9663
Epoch 32/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0866 - accuracy: 0.9659
Epoch 33/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0863 - accuracy: 0.9659
Epoch 34/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0860 - accuracy: 0.9661
Epoch 35/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0857 - accuracy: 0.9659
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0859 - accuracy: 0.9666: 0s - loss: 0.0861
Epoch 37/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0858 - accuracy: 0.9662
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0851 - accuracy: 0.9666
Epoch 39/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0852 - accuracy: 0.9665
Epoch 40/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0851 - accuracy: 0.9668
Epoch 41/50
804/804 [==============================] - 4s 4ms/step - loss: 0.0849 - accuracy: 0.9663
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0844 - accuracy: 0.9664
Epoch 43/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0846 - accuracy: 0.9666
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0839 - accuracy: 0.9670
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0845 - accuracy: 0.9668
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0839 - accuracy: 0.9666
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0838 - accuracy: 0.9666
Epoch 48/50
804/804 [==============================] - ETA: 0s - loss: 0.0836 - accuracy: 0.96 - 3s 4ms/step - loss: 0.0835 - accuracy: 0.9667
Epoch 49/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0835 - accuracy: 0.9670
Epoch 50/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0831 - accuracy: 0.9673

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [54]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
  2/268 [..............................] - ETA: 33s - loss: 2.9335 - accuracy: 0.5469WARNING:tensorflow:Callbacks method `on_test_batch_end` is slow compared to the batch time (batch time: 0.0030s vs `on_test_batch_end` time: 0.0462s). Check your callbacks.
268/268 [==============================] - 1s 5ms/step - loss: 2.7225 - accuracy: 0.5740
Loss: 2.7225162982940674, Accuracy: 0.5739941596984863

In [56]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 [==============================] - 1s 3ms/step - loss: 1.8991 - accuracy: 0.7964
Loss: 1.8991061449050903, Accuracy: 0.7963848114013672

In [57]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 [==============================] - 1s 3ms/step - loss: 0.5583 - accuracy: 0.7006
Loss: 0.5582852363586426, Accuracy: 0.700641393661499

### Step 3: Save each of your alternative models as an HDF5 file.

In [51]:
# Set the file path for the first alternative model
file_path = 'alternate_model_1.h5'

# Export your model to a HDF5 file
# YOUR CODE HERE
nn_A1.save(file_path)

In [52]:
# Set the file path for the second alternative model
file_path = 'alternate_model_2.h5'

# Export your model to a HDF5 file
nn_A2.save(file_path)